### ISSUE TITLE
Extend DB annotator to optional additional databases

### ISSUE THREAD

**Issue by incardon** [bihealth/varfish-annotator#24]
**Is your feature request related to a problem? Please describe.**
In research/clinical context additional scores are in general required.

**Describe the solution you'd like**
Expand init-db command to support additional databases

**Describe alternatives you've considered**
None

**Additional context**
None

**Implementation Proposal**
Add additional options for the following scores
 SpliceAI (PS I know CUBI has something already on that but I do not see something it in DBInit, may be some branch ?)
 REVEL
 CADD
 SIFT_pred
 Polyphen
 PROVEAN ()
 PromateAI ()

**Affected Components**
varfish-annotator

**Required Architectural Changes**
None

**Implementation Sketch**
Add parameters in DbInitArgs.java + one java file for each DB (REVEL ...)  all are added (concatenated) to the columns Extra Annos in JSON format
(The old JSON extra annos column is going to be overwritten by this procedure) 

(Tests ... not sure I saw any infrastructure for that)

**Comment by holtgrewe** [comment]
@incardon I believe this path is deprecated now in favour of an external variant annotation service in VarFish. If so, please confirm and close issue as "not planned".
