### ISSUE TITLE
VCF file looks like hg37 by chr1 length you required GRCh38 error

### ISSUE THREAD

**Issue by Saranya-Balachandran** [bihealth/varfish-annotator#98]
**Though the vcf ##contig=<ID=1,length=248956422>, the following error occurs - VCF file looks like hg37 by chr1 length you required GRCh38**
<img width="727" alt="image" src="https://github.com/bihealth/varfish-annotator/assets/27768663/61b33be6-9e91-4ee0-b22f-2da2af98d50e">
<img width="729" alt="image" src="https://github.com/bihealth/varfish-annotator/assets/27768663/a4a07583-3e94-4751-aeb6-644e2b60efbe">

**Comment by holtgrewe** [comment]
Hi @Saranya-Balachandran, thanks for the reporting the issue.

There is a bug in the following line:

https://github.com/bihealth/varfish-annotator/blob/5393f3cc90545685480f60ef488a09d9a4be83b1/varfish-annotator-core/src/main/java/com/github/bihealth/varfish_annotator/checks/VcfCompatibilityChecker.java#L82

I'll fit it and make a new annotator release.

**Comment by holtgrewe** [comment]
The new release in v0.33 should fix the issue.

https://github.com/bihealth/varfish-annotator/releases/tag/v0.33
